// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDv2OXDRBOfa5S54n8ZVK9skG3EvPb7l-Q',
    appId: '1:6212006149:web:ba92073840e182f00d476c',
    messagingSenderId: '6212006149',
    projectId: 'course-loading',
    authDomain: 'course-loading.firebaseapp.com',
    storageBucket: 'course-loading.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3Jf73ftvf9ebYYCb6gWFX9cXqX4ZRTsw',
    appId: '1:6212006149:android:db42e171e3dc8ede0d476c',
    messagingSenderId: '6212006149',
    projectId: 'course-loading',
    storageBucket: 'course-loading.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDO_q3-dEHsLWz7aSm4HIzNFZbdWlSZ5r0',
    appId: '1:6212006149:ios:cf576f9ec7b542dc0d476c',
    messagingSenderId: '6212006149',
    projectId: 'course-loading',
    storageBucket: 'course-loading.firebasestorage.app',
    iosBundleId: 'com.nickdieda.courseLoadingSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDO_q3-dEHsLWz7aSm4HIzNFZbdWlSZ5r0',
    appId: '1:6212006149:ios:cf576f9ec7b542dc0d476c',
    messagingSenderId: '6212006149',
    projectId: 'course-loading',
    storageBucket: 'course-loading.firebasestorage.app',
    iosBundleId: 'com.nickdieda.courseLoadingSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDv2OXDRBOfa5S54n8ZVK9skG3EvPb7l-Q',
    appId: '1:6212006149:web:e8b6fdfea1a166d10d476c',
    messagingSenderId: '6212006149',
    projectId: 'course-loading',
    authDomain: 'course-loading.firebaseapp.com',
    storageBucket: 'course-loading.firebasestorage.app',
  );
}
